python_library(
    name = "tags",
    srcs = ["tags.py"],
    visibility = ["PUBLIC"],
    deps = [
        "//tools/wheel_resolver/third_party/python:packaging",
        "//tools/wheel_resolver/third_party/python:distlib",
    ],
)
