subinclude("//build_defs:python")

python_library(
    name = "tags",
    srcs = ["tags.py"],
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/python:distlib",
        "//third_party/python:packaging",
        "//third_party/python:wheel_filename",
    ],
)
