subinclude("//test/build_defs:release_remote_file")

release_remote_file_hash_test(
    name = "please_pex_remote_hashes",
    release_file = "please_pex",
    remote_file_label = "//tools:please_pex",
)

