# TODO(jpoole): This should be a remove file on the plugin repo's release page and we should remove //_please:please_pex
filegroup(
    name = "please_pex",
    srcs = ["@//_please:please_pex"],
    visibility = ["PUBLIC"],
    labels = ["hlink:plz-out/package"]
)