# This test ensures that .pex files generated by python_binary are runnable when invoked from PATH.

set -euo pipefail

# Add the directory containing print_args.pex to the front of PATH.
export PATH="$PWD/$(dirname "$DATA_PEX"):$PATH"

# Invoke the .pex file as "print_args.pex". The .pex preamble should execute the run-time Python
# interpreter with $PWD/$DATA_PEX (i.e. the absolute path to print_args.pex) as the path to the
# script to execute.
if ! "$(basename "$DATA_PEX")" | grep -qFx "$PWD/$DATA_PEX"; then
    echo "$DATA_PEX was not invoked as expected"
    exit 1
fi
