plugin_repo(
    name = "go",
    revision = "v1.24.0",
)

plugin_repo(
    name = "shell",
    revision = "v0.1.2",
)

plugin_repo(
    name = "e2e",
    plugin = "plugin-integration-testing",
    revision = "v1.0.3",
)
