filegroup(
    name = "resolve",
    srcs = ["resolve.py"],
    visibility = ["PUBLIC"],
    deps = [
        "//tools/wheel_resolver/src/wheel_tags:tags",
        "//third_party/python:argparse",
    ],
)
