filegroup(
    name = "archs",
    srcs = ["archs.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "checksums",
    srcs = ["checksums.build_defs"],
    visibility = ["//build_defs/..."],
)

filegroup(
    name = "python",
    srcs = ["python.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "version",
    srcs = ["version.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "multiversion_wheel",
    srcs = ["multiversion_wheel.build_defs"],
    visibility = ["//third_party/..."],
)
