filegroup(
    name = "archs",
    srcs = ["archs.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "python",
    srcs = ["python.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "version",
    srcs = ["version.build_defs"],
    visibility = ["PUBLIC"],
)
