go_library(
    name = "pex",
    srcs = ["pex.go"],
    resources = glob(["**/*.py"]),
    # visibility = ["//tools/pleeeease_pex:all"],
    visibility = ["//tools/chicken_pex:all"],
    deps = [
        #"//tools/jarcat/zip",
    ],
)
