subinclude("//build_defs:python")

python_test(
    name = "site_test",
    srcs = ["site_test.py"],
    site = True,
)

python_test(
    name = "no_site_test",
    srcs = ["no_site_test.py"],
    site = False,
)
