python_binary(
    name = "wheel_resolver",
    main = "//tools/wheel_resolver/src:resolve",
    visibility = ["PUBLIC"],
#     deps = [
#         "//tools/wheel_resolver/src/tags:tags",
#         "//tools/wheel_resolver/third_party/python:argparse",
#     ],
)
