python_binary(
    name = "wheel_resolver",
    main = "//tools/wheel_resolver/src:resolve",
    visibility = ["PUBLIC"],
    deps = [
        "//tools/wheel_resolver/src/wheel_tags:tags",
        "//third_party/python:argparse",
    ],
)
