# go_library(
#     name = "zip",
#     srcs = ["writer.go"],
#     visibility = [
#         "//tools/jarcat:all",
#         "//tools/please_pex/pex",
#     ],
#     deps = [
#         "//third_party/go:go-logging.v1",
#         "//third_party/go:testify",
#         "//third_party/go/zip",
#     ],
# )

# go_module(
#     name = "zip",
#     licences = ["BSD-3-Clause"],
#     module = "gopkg.in/archive/zip",
#     version = "go1.17.3",
# )

# go_test(
#     name = "writer_test",
#     srcs = ["writer_test.go"],
#     data = [
#         "test_data",
#         "test_data_2",
#         "test_data_3",
#     ],
# )
